plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.google.services)
}

android {
    namespace 'com.example.inventario_ra'
    compileSdk 37

    defaultConfig {
        applicationId "com.example.inventario_ra"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {

        // Formato CamelCase para evitar booilerplate (lineasinncesarias)
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    packaging {
        jniLibs {
            // Requerido para compatibilidad con 16 KB en Android 15+
            useLegacyPackaging = false
        }
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation(libs.assets) {
        exclude group: 'com.google.ar.sceneform', module: 'sceneform-base'
        exclude group: 'com.google.ar.sceneform', module: 'core'
    }
    implementation libs.constraintlayout

    // Material Design para la UI
    implementation libs.material

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // Firebase BoM (Bill of Materials) para asegurar compatibilidad de versiones
    implementation platform(libs.firebase.bom) // Ultima Version del BoM
    implementation 'com.google.firebase:firebase-analytics'
    implementation libs.firebase.database // Para texto y stock [cite: 3, 11]
    implementation libs.firebase.storage // Para imágenes y modelos 3D

    // ARCore
    implementation libs.core

    // SceneView (Libreria moderna para renderizado 3D y AR en Java/Kotlin - Compatible con 16 KB)
    implementation libs.arsceneview


    // Google Play Services para Geolocalización (GPS)
    implementation libs.play.services.location
    implementation libs.play.services.maps


    //Motor de Descarga y Renderizado para IMG en Firebase y Material Desing
    implementation libs.glide
    annotationProcessor libs.compiler

    //Flujo de Navegacion simple y Ordenado
    implementation libs.navigation.fragment
    implementation libs.navigation.ui

}